sudo: true
dist: trusty
language: clojure
notifications:
  email:
  - antonin@hildebrand.cz
  hipchat:
    rooms:
      secure: jVepqbnkon7Z1lcUQbI2vVjMnYHwqIxQviItnmP4nYdkfNEFZCHQ2aG+cqDYfTs39qmcOqEnPjfvErm7U7JvC7G6xibSHDT79gFtJ2z1T+Cd0jDwoHDc8qhq8I9lTxs0S5Cv4r0lAKbtJO2b4VNrJXLrmxXG37HQS/6vstHjYMIlQ26YZSrQrlBkkH96mC9jZ7OeB6wOrnvJ4Y9aUU69jr4hVmL+oofhYWsq13vnq9QErCsAi6ILKKTubeuLjG9vgLilrtccyEyOnA2yKwutk1WBzJ6ewifoDKtpUaETaSS4PdVKVsoGQbsytPWlpKFFNJzL8jF8LFAHTrAxJcER26iHGGeafn4b/z5qCft+IpyA3zH1HnX4ixS/aBlb8t0p/P4gs+/Ac2yiSbCGycTdPo6Hu9yJcXn7OtCHz78eOjy0zT+wfCRy4y0E4nZPNU2R9JXhP4v08ruRG4UFXFk0bgsHaOKp1d0GBxoknUbWr7s2PgRAf2vuWORnf3iAsHyxok7fhg2aO3bGXB/fZYnXnziGV5Scto644cRcQS0+vY/70sta42ADU+R6P4RDkavtSeEHLj7AcgalIxJZev4yIbItvD/ZYJBafzqd074eOdt0+I7kkCdywdqygmIdNBiSO7FOgoage0qXdSw9ho3sAauh9xdkAJcIss43Uxzb/1Y=
cache:
  directories:
  - "$HOME/.m2"
script: scripts/travis-entrypoint.sh
